#!/bin/bash
set -eu

sed -i "s/^\(myhostname =\).*/\1 $POSTFIX_FQDN/" /etc/postfix/main.cf

service postfix restart

# TODO: replace this later with something more useful
tail -f /var/log/bootstrap.log
